version: '3.4'

services:
  parksite:
    image: ${DOCKER_REGISTRY-}parksite:${TAG-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80


